### ISSUE TITLE
TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by bitbrain** [jverhoelen/golumbus#7]
When typing `goto location` and `location` is not a registered location, the following error is thrown:

```
/usr/local/lib/node_modules/golumbus/index.js:51
        console.log(config.entries[name].path.rainbow);
                                        ^

TypeError: Cannot read property 'path' of undefined
    at Command.<anonymous> (/usr/local/lib/node_modules/golumbus/index.js:51:41)
    at Command.listener (/usr/local/lib/node_modules/golumbus/node_modules/commander/index.js:301:8)
    at emitOne (events.js:90:13)
    at Command.emit (events.js:182:7)
    at Command.parseArgs (/usr/local/lib/node_modules/golumbus/node_modules/commander/index.js:617:12)
    at Command.parse (/usr/local/lib/node_modules/golumbus/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/golumbus/index.js:117:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by jonas-pietzsch** [comment]
This should already have been fixed in 0.0.5 and works on the current master. If not already included in the 0.0.5 NPM release, it will be in 0.0.6 within the next days ;-)
